#!/bin/bash
# Format directory to feed to LLM

find . -type f | while read -r file; do
    if file --mime-type "$file" | grep -q ': image/.\+$'; then
        continue
    fi

    echo "File : $file"
    echo "\`\`\`"
    cat "$file"
    echo "\`\`\`"
    echo "-------------------"
    echo ""
done
