theme = "papercolor-dark"

[editor]
line-number = "relative"
cursorline = true
cursorcolumn = true
idle-timeout = 0
completion-trigger-len = 1
bufferline = "multiple"
color-modes = true
 
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spacer", "version-control", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "read-only-indicator", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true
