theme = "papercolor-dark"

[editor]
line-number = "relative"
cursorline = true
cursorcolumn = true
idle-timeout = 0
completion-trigger-len = 1
bufferline = "multiple"
color-modes = true
auto-save = true 
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true

[editor.statusline]
left = ["mode", "spacer", "version-control", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "read-only-indicator", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[keys.normal]
"r" = ":config-reload"
"{" = "jump_backward"
"}" = "jump_forward"
"S-esc" = ":buffer-close"
"S-left" = "goto_previous_buffer"
"S-right" = "goto_next_buffer"
"?" = "toggle_comments"

[keys.select]
"?" = "toggle_comments"
