theme = "gruvbox_dark_hard"

[editor]
line-number = "relative"
cursorline = true
cursorcolumn = true
idle-timeout = 1
completion-trigger-len = 1
bufferline = "multiple"
color-modes = true
true-color = true
popup-border = "all"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.statusline]
left = ["mode", "spacer", "version-control", "spinner"]
center = ["file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "position", "position-percentage", "total-line-numbers", "file-encoding", "file-type", "read-only-indicator"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.file-picker]
hidden = false
parents = false
ignore = true
git-ignore = false
git-global = false
git-exclude = false

[editor.indent-guides]
render = true

[keys.normal]
"r" = ":config-reload"
"{" = "jump_backward"
"}" = "jump_forward"
"_" = ":buffer-close"
"S-left" = "goto_previous_buffer"
"S-right" = "goto_next_buffer"
"?" = "toggle_comments"
"S-up" = ["goto_line_end","extend_line_below", "delete_selection", "move_line_up", "paste_before"]
"S-down" = ["goto_line_end","extend_line_below", "delete_selection", "paste_after"]

[keys.insert]
"S-left" = ["select_mode", "goto_previous_buffer"]
"S-down" = ["goto_line_end","extend_line_below", "delete_selection", "paste_after"]

[keys.select]
"S-up" = ["goto_line_end","extend_line_below",  "delete_selection", "move_line_up", "paste_before", "select_mode"]
"S-down" = ["goto_line_end","extend_line_below",  "delete_selection", "paste_after", "select_mode" ]
"?" = "toggle_comments"
